// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDzsF5aH00lQ9YDUJ10LckajOp07jJh1Mg',
      appId: '1:584417502330:android:8747ee4203d5742b7687c3',
      messagingSenderId: '584417502330',
      projectId: 'flutter-travel-project-f054b',
      storageBucket: 'flutter-travel-project-f054b.appspot.com');

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyC-4H82oAJ1y5MiG2E-WEKNjQsjELlkFcs',
      authDomain: 'flutter-travel-app-2b046.firebaseapp.com',
      projectId: 'flutter-travel-app-2b046',
      storageBucket: 'flutter-travel-app-2b046.appspot.com',
      messagingSenderId: '466832606382',
      appId: '1:466832606382:web:f205552709a969d98c193f');
}
